// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPokemonImage(arg1:Array<number>):Promise<string>;

export function GetPokemonName(arg1:number,arg2:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function TTS(arg1:string):Promise<boolean>;

export function TakePic():Promise<string>;
