// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPokemonImage(arg1) {
  return window['go']['main']['App']['GetPokemonImage'](arg1);
}

export function GetPokemonName(arg1, arg2) {
  return window['go']['main']['App']['GetPokemonName'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
