// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetOptions(arg1) {
  return window['go']['main']['App']['GetOptions'](arg1);
}

export function GetPokemonId(arg1) {
  return window['go']['main']['App']['GetPokemonId'](arg1);
}

export function GetPokemonImage(arg1) {
  return window['go']['main']['App']['GetPokemonImage'](arg1);
}

export function GetPokemonName(arg1, arg2) {
  return window['go']['main']['App']['GetPokemonName'](arg1, arg2);
}

export function GetPokemonNameForGuess(arg1) {
  return window['go']['main']['App']['GetPokemonNameForGuess'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PlayTTS() {
  return window['go']['main']['App']['PlayTTS']();
}

export function TTS(arg1) {
  return window['go']['main']['App']['TTS'](arg1);
}

export function TakePic() {
  return window['go']['main']['App']['TakePic']();
}
